### ISSUE TITLE
Not compatible with Python3

### ISSUE THREAD

**Issue by spacecowboy** [PaulGregor/crowdin-cli#2]
Might send a pull request for this at some point..

**Comment by key** [comment]
+1

**Comment by PaulGregor** [comment]
Thanks, I will release update, where Python 3 compatibility is implemented,  at February.

**Comment by PaulGregor** [comment]
I did rewrite some parts of the code, so now crowdin-cli-py is compatible with Python3.

**Comment by spacecowboy** [comment]
:+1:

**Comment by stefanhoth** [comment]
Just to mention. I tried it first to use it on Windows via Python3 and it failed, complaining about syntax. Uninstall, reinstall via Python2 and it worked fine. So maybe it was not totally finished? :smile:

**Comment by spacecowboy** [comment]
@stefanhoth The log you posted seems inconsistent with the file contents on the master branch. So it's just that the latest version is not up on PyPi yet. Try installing straight from github:

    pip install git+https://github.com/PaulGregor/crowdin-cli.git

**Comment by stefanhoth** [comment]
@spacecowboy A thanks. I just read "the new version" and assumed it's released as well. Thanks!

**Comment by PaulGregor** [comment]
Hi there.
I uploaded new version to PyPi with all new features, so you may now upgrade. 

    pip install --upgrade crowdin-cli-py
