### ISSUE TITLE
Warning: Downloaded translations do not match current project configuration for en-US and en languaege in one project

### ISSUE THREAD

**Issue by Slach** [PaulGregor/crowdin-cli#6]
i have following localization project file structure

source files
<pre>
lang/ru.lproj/common/datapack.po
lang/ru.lproj/common/dialogs.po
</pre>

with two language translations en
<pre>
lang/en.lproj/common/datapack.po
lang/en.lproj/common/dialogs.po
</pre>

and  en-US
<pre>
lang/en_US.lproj/common/datapack.po
lang/en_US.lproj/common/dialogs.po
</pre>

and have two configs for separate language (en and en_US) workflow

crowdin_config_ISO-639.yml
<pre>
api_key: XXX
base_path: XXX
files:
- {source: /lang/ru.lproj/common/datapack.po, translation: /lang/%two_letters_code%.lproj/common/%original_file_name%}
- {source: /lang/ru.lproj/common/dialogs.po, translation: /lang/%two_letters_code%.lproj/common/%original_file_name%}
project_identifier: XXX
</pre>

and crowdin_config_RFC-3066.yml
<pre>
api_key: XXX
base_path: XXX
files:
- {source: /lang/ru.lproj/common/datapack.po, translation: /lang/%locale_with_underscore%.lproj/common/%original_file_name%}
- {source: /lang/ru.lproj/common/dialogs.po, translation: /lang/%locale_with_underscore%.lproj/common/%original_file_name%}
project_identifier: XXX
</pre>

when i run UPLOAD workflow 
<pre>
crowdin-cli-py -c crowdin_config_ISO-639.yml upload sources
crowdin-cli-py -c crowdin_config_ISO-639.yml upload translations -l en
crowdin-cli-py -c crowdin_config_RFC-3066.yml upload translations -l en-US
</pre>
upload working FINE

but when i run Download workflow
<pre>
crowdin-cli-py -c crowdin_config_ISO-639.yml download -l en
crowdin-cli-py -c crowdin_config_RFC-3066.yml download -l en-US
</pre>
for en_US language i have strange warning
<pre>
Warning: Downloaded translations do not match current project configuration. Some of the resulted files will be omitted.
</pre>

and en-US.zip unpacked to wrong language:
<pre>
lang/en.lproj/common/datapack.po
lang/en.lproj/common/dialogs.po
</pre>

how i can change file structure to try fix it?

**Comment by Slach** [comment]
i try change crowdin_config_RFC-3066.yml 
and add
<pre>
languages_mapping:
    locale_with_underscore:
        # crowdin_language_code: local_name
        en: en
        en-US: en_US
</pre>

without any effect

**Comment by PaulGregor** [comment]
Hi there! I've recreated and tested it with your configs. During that I haven't spotted 
<pre>
Warning: Downloaded translations do not match current project configuration. Some of the resulted files will be omitted.
</pre>
download works perfectly for both en and en_US. 
There is some warning in project settings page from crowdin but I don't know if it has any effects:
<pre>
If incorrect variables are used for resulting file names, during the export some languages might be overwritten by other languages which share the same code.
For example, if %two_letters_code% variable is used and there are Portuguese and Portuguese, Brazilian target languages in the project, exported translations will be placed in the same directory — pt.
We strongly recommend to switch to another allowed variables to prevent any issues whilst the project build.
</pre>
I was using crowdin-cli-py v. 0.95.2,  Russian as source language, English and English, United States as target languages.

**Comment by PaulGregor** [comment]
Oh, my bad it's not working correctly. I tasted your configs on different projects and did see a warning you have mentioned. This is what I figured out:

if you are using %two_letters_code%  and make "upload sources && upload translation" than all download translations will be placed on "en.lproj" even if you use 'another config with %locale_with_underscore% ' or 'download -l en-US'  . **Its because of that warning from crowdin.** 

To make download command put translations in "en_US.lproj directory" you need use a config with '%locale_with_underscore%' than make "upload sources && upload translation", it will overwrite project settings on crodwin, and allow you after 'projects is built again' download en_US translations correctly.

**Comment by Slach** [comment]
thanks for quick reply

i merge two different config to one
with %osx_code% placeholder
<pre>
api_key: XXX
base_path: XXX
files:
- {source: /lang/ru.lproj/common/datapack.po, translation: /lang/%osx_code%/common/%original_file_name%}
- {source: /lang/ru.lproj/common/dialogs.po, translation: /lang/%osx_code%/common/%original_file_name%}
project_identifier: melesta-coffee-alconost
</pre>

and use 
en.lproj
en_US.lproj
for language catalog directory names

and use following workflow
<pre>
crowdin-cli-py -c crowdin_config.yml upload sources
crowdin-cli-py -c crowdin_config.yml upload translations -l en-US
crowdin-cli-py -c crowdin_config.yml upload translations -l en
</pre>

<pre>
crowdin-cli-py -c crowdin_config.yml upload translations -l en
crowdin-cli-py -c crowdin_config.yml upload translations -l en-US
</pre>
